name: Push to Replicate (Definitive)

on:
  workflow_dispatch:
    inputs:
      model_name:
        description: 'Enter the model name, like "your-username/aura-color-analysis"'
        required: true

jobs:
  push_to_replicate:
    name: Push to Replicate
    runs-on: ubuntu-latest
    steps:
      - name: Free disk space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          tool-cache: false
          docker-images: false

      - name: Checkout repository code
        uses: actions/checkout@v4

      - name: Setup Cog tool
        uses: replicate/setup-cog@v2
        with:
          token: ${{ secrets.REPLICATE_API_TOKEN }}

      # ==========================================================
      # THE "SOLVE THIS FOREVER" SCRIPT
      # ==========================================================
      - name: Find and Push from Correct Directory
        run: |
          echo "Searching for cog.yaml in the entire workspace..."
          
          # Find the directory containing cog.yaml
          # 'find . -name cog.yaml' searches for the file
          # 'xargs dirname' gets the directory path of the found file
          COG_DIR=$(find . -name cog.yaml -print -quit | xargs dirname)
          
          if [ -z "$COG_DIR" ]; then
            echo "::error::Could not find cog.yaml anywhere in the checkout. Listing all files for debugging:"
            ls -R
            exit 1
          fi
          
          echo "Found cog.yaml in directory: $COG_DIR"
          echo "Changing to that directory and pushing to Replicate..."
          
          # Change to the correct directory and then run the push command
          cd "$COG_DIR" && cog push r8.im/${{ inputs.model_name }}